#!/usr/bin/env bash

# Function to display information about a subdomain
function display_info() {
  local subdomain="$1"
  local domain="$2"
  local record_type="$3"
  local destination="$4"
  echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Check if both domain and subdomain are provided
if [ $# -eq 2 ]; then
  domain="$1"
  subdomain="$2"

  # Use dig to retrieve DNS information and awk to parse it
  dns_info=$(dig +short "$subdomain.$domain")

  # Determine the record type (A or CNAME) and destination
  if [[ $dns_info =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    record_type="A"
    destination="$dns_info"
  else
    record_type="CNAME"
    destination="$dns_info"
  fi

  display_info "$subdomain" "$domain" "$record_type" "$destination"
else
  # If only domain is provided, display information for specific subdomains
  domain="$1"
  subdomains=("www" "lb-01" "web-01" "web-02")

  for subdomain in "${subdomains[@]}"; do
    dns_info=$(dig +short "$subdomain.$domain")
    
    # Determine the record type (A or CNAME) and destination
    if [[ $dns_info =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      record_type="A"
      destination="$dns_info"
    else
      record_type="CNAME"
      destination="$dns_info"
    fi

    display_info "$subdomain" "$domain" "$record_type" "$destination"
  done
fi
