#!/usr/bin/env bash
# copy and paste the fullchain and private key on single file.
# and apply permission mod and ownership to approxy

sudo chown haproxy:haproxy /etc/letsencrypt/live/www.francisntima.tech/www.francisntima.pem
sudo chmod 644 /etc/letsencrypt/live/www.francisntima.tech/www.francisntima.pem

# Change the path at your bind with the applied changes
# but this command will auto direct your to the file
sudo vi /etc/haproxy/haproxy.cfg

# This run haproxy test to see if the changes are correctly
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
