#!/usr/bin/env bash
# A bash script that transfers a file
# from our client to a server


# This checks required number of parameters if provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# This disable the strict host key checking
SSH_HOST="-o StrictHostKeyChecking=no"

# This transfer file to the user's home directory
# on the mentioned server
scp $SSH_HOST -i "$4" "$1" "$3@$2:~/"

# This checks if the file transfer was sent successful
if [ $? -eq 0 ]; then
    echo "File transfer successful."
else
    echo "File transfer failed."
fi
