#!/usr/bin/env bash
#  Redirection bash script

# This will Install nginx
apt-get update -y
apt-get install nginx -y

# This create a basic HTML file containing "Hello World!"
echo "<html><body>Hello World!</body></html>" > /var/www/html/index.html

# This checks Nginx if not already running
if [ ! -f /var/run/nginx.pid ]; then
    # Then starts Nginx
    /usr/sbin/nginx
fi

# This checks if Nginx listening on port 80
if ! netstat -tuln | grep ":80 " > /dev/null; then
    echo "Nginx is not listening on port 80. Please check the configuration."
    exit 1
fi

# This create a new Nginx configuration file for redirection
echo "server {
    listen 80;
    server_name _;
    location = /redirect_me {
        return 301 https://youtube.com/;
    }
}" > /etc/nginx/sites-available/redirect

# This will reate a symbolic link to enable the configuration
ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/
nginx -t # Test for Nginx configuration
nginx -s reload # Reload Nginx to apply the new configuration

# Clean up default Nginx configuration files
rm /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
service nginx restart # Restart Nginx
