#!/usr/bin/env bash

# First Installing nginx
apt-get update -y
apt-get install nginx -y

# This configure the redirection page
echo "server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 https://francisntima.tech/redirect_me;
    }
}" > /etc/nginx/sites-available/redirect

# makes sure that default is removed
# And restarts the server
ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/
nginx -t && service nginx restart
rm /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
