#!/usr/bin/env bash
#  Redirection bash script

# This will Install nginx
apt-get update -y
apt-get install nginx -y


# Gain root privileges On server.
sudo -i

# This create a basic HTML file containing "Hello World!"
echo "<html><body>Hello World!</body></html>" > /var/www/html/index.html

# This creates a custom 404 error page with a message.
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Use sed to modify the Nginx default configuration to include the custom 404 error page.
sed -i "s/server_name _;/server_name _;\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}/" /etc/nginx/sites-available/default

# This start the Nginx service
sudo service nginx start
