#!/usr/bin/env bash
# Web-Server_02 login Infos.

# setting ssh agent
eval $("ssh-agent")

# Path to file Identification
ssh-add ~/.ssh/school

# Username name and IP-Address
ssh -i ~/.ssh/id_rsa ubuntu@54.162.38.26
