#!/usr/bin/env bash
# Web Server Setup Configuration file with
# Redirect_me And Page Not Found file.

# nginx server update and installation.
sudo apt-get update
sudo apt-get install -y nginx

# Redirection file.
str="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/vloneme permanent;"
sudo sed -i "s/server_name _;/$str/" /etc/nginx/sites-enabled/default

# custom 404 not found page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$str/" /etc/nginx/sites-enabled/default

# Check configurations for syntax errors
sudo nginx -t

# This restart nginx after implementing changes
sudo service nginx restart
