#!/usr/bin/env bash
# Bash script that creates /var/run/holbertonscript.pid with its PID

echo $$ > /var/run/holbertonscript.pid

# Trap SIGTERM and SIGQUIT signals
trap "echo I hate the kill command ; rm /var/run/holbertonscript.pid ; exit" SIGTERM SIGQUIT

# Trap SIGINT signal
trap "echo Y U no love me?! ; exit" SIGINT

# Display "To infinity and beyond" indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
done
