#!/usr/bin/env bash
# Bash script that creates /var/run/holbertonscript.pid with its PID

trap "echo I hate the kill command ; rm /var/run/holbertonscript.pid ; exit" SIGTERM SIGQUIT
trap "echo Y U no love me?! ; exit" SIGINT

pidof bash >> /var/run/holbertonscript.pid
while ((1)); do
    echo "To infinity and beyond"
    sleep 2
done
