#!/bin/env bash
# Bash script that displays Best School 10 times

num=1
while [[ $i -le 10 ]]
do
    echo "Holberton School"
    if [ "$i" -eq "9" ]
    then
	echo "Hi"
    fi
    num=$(( num + 1 ))
done
