#!/bin/env bash
# Initial counter

count=1

# Bash script that displays Best School 10 times
while [ $count -le 10 ]
do
    echo  "Best School "

    # condition flow
    if [ $count -eq 9 ]
    then
	echo  "Best School "
        echo  "Hi"
    fi
    ((count++))
done
