#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.

# Set a user in the Nginx configuration by replacing '#user' with its value
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Replace port 80 with 8080 in the sites-available configuration
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Grant owner permissions to read and write to the Nginx configuration file
chmod 644 /etc/nginx/nginx.conf

# Check for the presence of Apache and terminate its process if it's running
pkill apache2

# Start the Nginx service with the new 'nginx' user
sudo -u nginx service nginx start
