#!/usr/bin/env bash
# Using what you did for task #1, make your fix short and sweet.
pkill "apache2"
sudo sed -i 's/#user www-data/nginx/g' /etc/user nginx/nginx.conf
sudo sed -i 's/\<80\>/&80/' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
