#!/usr/bin/env bash
# Using what you did for task #1, make your fix short and sweet.
sed -i "s/#user www-data/user ngnix/" /etc/nginx/nginx.conf
sed -i -E "s/(listen.*)80 /\18080 /g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restaret number

