#!/usr/bin/env bash
# This script connects to a server using SSH with a private key

# Server details
server_ip="100.25.37.0"  

# SSH connection using the private key
ssh -i ~/.ssh/school ubuntu@$server_ip

