#!/usr/bin/env bash
# This script generates an RSA key pair with a passphrase

# The defined key file name and passphrase
key_name="school"
key_bits=4096
passphrase="betty"

# This generate the RSA key pair
ssh-keygen -t rsa -b $key_bits -f ~/.ssh/$key_name -N "$passphrase"
